---
version: '2.4'

volumes:
#  prometheus_metrics:
#    driver: local
#    driver_opts:
#      device: $COMPOSEPATH/data/prometheus/metrics
#      o: bind
#      type: bind
  prometheus_etc:
    driver: local
    driver_opts:
      device: $COMPOSEPATH/data/prometheus/etc
      o: bind
      type: bind
  promvm_data:
    driver: local
    driver_opts:
      device: $COMPOSEPATH/data/promvm
      o: bind
      type: bind
  promgrafana_etc:
    driver: local
    driver_opts:
      device: $COMPOSEPATH/data/promgrafana/etc
      o: bind
      type: bind
  promgrafana_db:
    driver: local
    driver_opts:
      device: $COMPOSEPATH/data/promgrafana/db
      o: bind
      type: bind
  promgrafana_plugins:
    driver: local
    driver_opts:
      device: $COMPOSEPATH/data/promgrafana/plugins
      o: bind
      type: bind
  promgrafana_dashboards:
    driver: local
    driver_opts:
      device: $COMPOSEPATH/data/promgrafana/etc/dashboards
      o: bind
      type: bind
  alertmanager_etc:
    driver: local
    driver_opts:
      device: $COMPOSEPATH/data/alertmanager/etc
      o: bind
      type: bind
  sentryredis_data:
    driver: local
    driver_opts:
      device: $COMPOSEPATH/data/sentry/redis
      o: bind
      type: bind
  sentrypostgres_data:
    driver: local
    driver_opts:
      device: $COMPOSEPATH/data/sentry/pg
      o: bind
      type: bind

services:
#  prom:
#    image: prom/prometheus:v2.11.1
#    restart: always
#    hostname: prom
#    volumes:
#      - prometheus_etc:/etc/prometheus
#      - prometheus_metrics:/prometheus-data
#    command: >
#        --config.file=/etc/prometheus/prometheus.yml
#        --storage.tsdb.path=/prometheus-data
#        --storage.tsdb.retention.time=12h
#        --web.external-url=https://prom:9090
#        --query.max-concurrency=40
#        --query.timeout=20s
#    ports:
#      - "9090:9090"
#    logging:
#      driver: $COMPOSE_LOG_DRIVER
#      options:
#        max-size: $COMPOSE_LOG_MAX_SIZE
#        max-file: $COMPOSE_LOG_MAX_FILE
#    labels:
#      - traefik.enable=false

  promgrafana:
    image: grafana/grafana:6.3.6
    restart: always
    hostname: prometheusgrafana
    env_file:
      - .env.proxy
    volumes:
      - promgrafana_etc/:/etc/grafana
      - promgrafana_db:/var/lib/grafana/
      - promgrafana_plugins:/var/lib/grafana/plugins
      - promgrafana_dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - vm
    environment:
      GF_SERVER_ROOT_URL: https://promgrafana
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_INSTALL_PLUGINS: grafana-simple-json-datasource,
                          vertamedia-clickhouse-datasource
    logging:
      driver: $COMPOSE_LOG_DRIVER
      options:
        max-size: $COMPOSE_LOG_MAX_SIZE
        max-file: $COMPOSE_LOG_MAX_FILE
    labels:
      - traefik.enable=false

  vm:
    container_name: vm
    hostname: vm
    restart: always
    image: victoriametrics/victoria-metrics:v1.37.0
    volumes:
      - promvm_data:/storage
    command: >
        -storageDataPath=/storage
        -retentionPeriod=3
        -httpListenAddr=:8428
    logging:
      driver: $COMPOSE_LOG_DRIVER
      options:
        max-size: $COMPOSE_LOG_MAX_SIZE
        max-file: $COMPOSE_LOG_MAX_FILE
    labels:
      - traefik.enable=false

#  vmalert:
#    container_name: vmalert
#    hostname: vmalert
#    restart: always
#    image: victoriametrics/vmalert:v1.37.0
#    volumes:
#      - promvm_data:/storage
#    command: >
#        -storageDataPath=/storage
#        -retentionPeriod=3
#        -httpListenAddr=:8428
#    logging:
#      driver: $COMPOSE_LOG_DRIVER
#      options:
#        max-size: $COMPOSE_LOG_MAX_SIZE
#        max-file: $COMPOSE_LOG_MAX_FILE
#    labels:
#      - traefik.enable=false

  vmagent:
    container_name: vmagent
    hostname: vmagent
    restart: always
    image: victoriametrics/vmagent:v1.37.0
    volumes:
      - prometheus_etc:/etc/prometheus
    command: >
        -promscrape.config=/etc/prometheus/prometheus.yml
        -remoteWrite.url=https://vm:8428/api/v1/write
        -envflag.enable
#        -selfScrapeInterval=10s
    logging:
      driver: $COMPOSE_LOG_DRIVER
      options:
        max-size: $COMPOSE_LOG_MAX_SIZE
        max-file: $COMPOSE_LOG_MAX_FILE
    labels:
      - traefik.enable=false

  promclickhouse:
    image: f1yegor/clickhouse-exporter
    restart: always
    command: -scrape_uri=http://default:@clickhouse:8123/
    logging:
      driver: $COMPOSE_LOG_DRIVER
      options:
        max-size: $COMPOSE_LOG_MAX_SIZE
        max-file: $COMPOSE_LOG_MAX_FILE
    labels:
      - traefik.enable=false

  # read ./data/alertmanager/etc/Readme.md before start container
  alertmanager:
    image: prom/alertmanager:latest
    restart: always
    hostname: alertmanager
    volumes:
      - alertmanager_etc:/etc/alertmanager
    ports:
      - "9093:9093"
    command: >
        --config.file=/etc/alertmanager/alertmanager.conf
        --log.level=info
    logging:
      driver: $COMPOSE_LOG_DRIVER
      options:
        max-size: $COMPOSE_LOG_MAX_SIZE
        max-file: $COMPOSE_LOG_MAX_FILE
    labels:
      - traefik.enable=false

  prommongo:
    image: eses/mongodb_exporter
    restart: always
    hostname: prommongo
    command: >
        -mongodb.uri=mongodb://noc:$NOC_MONGO_PASSWORD@mongo:27017
    logging:
      driver: $COMPOSE_LOG_DRIVER
      options:
        max-size: $COMPOSE_LOG_MAX_SIZE
        max-file: $COMPOSE_LOG_MAX_FILE
    labels:
      - traefik.enable=false

  sentry-redis:
    image: redis:alpine
    hostname: sentry-redis
    restart: always
    volumes:
      - sentryredis_data:/data
    logging:
      driver: $COMPOSE_LOG_DRIVER
      options:
        max-size: $COMPOSE_LOG_MAX_SIZE
        max-file: $COMPOSE_LOG_MAX_FILE
    labels:
      - traefik.enable=false

  sentry-postgres:
    image: postgres:9.6-alpine
    hostname: sentry-postgres
    restart: always
    env_file:
      - ./data/sentry/sentry.env
    volumes:
      - sentrypostgres_data:/var/lib/postgresql/data
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    logging:
      driver: $COMPOSE_LOG_DRIVER
      options:
        max-size: $COMPOSE_LOG_MAX_SIZE
        max-file: $COMPOSE_LOG_MAX_FILE
    labels:
      - traefik.enable=false

  # after firsh start need run
  # cd $INSTALLPATH && docker-compose exec sentry sentry upgrade
  # for run migration and setup admin user\passwd
  sentry:
    image: sentry:9
    hostname: sentry
    restart: always
    links:
      - sentry-redis
      - sentry-postgres
    command: "sentry run web -w 4"
    ports:
      - "9000:9000"
    env_file:
      - ./data/sentry/sentry.env
    logging:
      driver: $COMPOSE_LOG_DRIVER
      options:
        max-size: $COMPOSE_LOG_MAX_SIZE
        max-file: $COMPOSE_LOG_MAX_FILE
    labels:
      - traefik.enable=false
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  sentry-cron:
    image: sentry:9
    hostname: sentry-cron
    restart: always
    links:
      - sentry-redis
      - sentry-postgres
    command: "sentry run cron"
    env_file:
      - ./data/sentry/sentry.env
    logging:
      driver: $COMPOSE_LOG_DRIVER
      options:
        max-size: $COMPOSE_LOG_MAX_SIZE
        max-file: $COMPOSE_LOG_MAX_FILE
    labels:
      - traefik.enable=false

  sentry-worker:
    image: sentry:9
    hostname: sentry-worker
    restart: always
    links:
      - sentry-redis
      - sentry-postgres
    command: "sentry run worker"
    env_file:
      - ./data/sentry/sentry.env
    logging:
      driver: $COMPOSE_LOG_DRIVER
      options:
        max-size: $COMPOSE_LOG_MAX_SIZE
        max-file: $COMPOSE_LOG_MAX_FILE
    labels:
      - traefik.enable=false
